### ISSUE TITLE
Changing search tabs doesn't populate results

### ISSUE THREAD

**Issue by ecxyzzy** [icssc/peterportal-client#352] opened 2023-09-20 05:13 UTC
On the first page load, when switching to the professors tab from the courses tab (and vice versa), the list of courses/professors is not populated. The user must type a keyword into the search bar or reload the page for the list to be populated.

**Comment by js0mmer** [comment] 2023-09-20 05:55
Duplicate of #305

**Closed by js0mmer** 2023-09-20 05:55 UTC
Labels: bug
