### ISSUE TITLE
PeterPortal Roadmap showing a black screen after logging in 

### ISSUE THREAD

**Issue by charlieweinberger** [icssc/peterportal-client#502] opened 2024-11-08 07:50 UTC
I went to https://peterportal.org/roadmap/ and began adding classes, as usual. Then, I noticed I could sign in and save my process, so I proceeded to sign in with my UCI email. Once I did so, when I returned to https://peterportal.org/roadmap/, I saw a glimpse of the roadmap as usual, but after half a second or so, I was greeted by a black screen. The continues to happen, even after reloading the page multiple times or signing out and back in again. After checking the devtools console, I see that the error messages below appear at the same time as the page goes black.

<img width="543" alt="Screenshot 2024-11-07 at 11 47 58 PM" src="https://github.com/user-attachments/assets/4222dd8b-45db-4c19-b8b1-15823b481469">

**Comment by Awesome-E** [comment] 2024-11-08 08:07
It looks like this is causing the exception, and it's likely due to part of a recent migration not working:
https://github.com/icssc/peterportal-client/blob/main/site/src/pages/RoadmapPage/YearModal.tsx#L26

@js0mmer can you investigate whether quarter names being passed into this function are consistent with existing user roadmaps?

**Comment by js0mmer** [comment] 2024-11-08 21:06
@Awesome-E I was able to reproduce and put up a PR to fix. #503

**Comment by js0mmer** [comment] 2024-11-13 22:42
This should be fixed now, let me know if you still have any issues.

**Closed** 2024-11-13 22:41 UTC
